// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://qyxrtuieqztyiguxlyet.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5eHJ0dWllcXp0eWlndXhseWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE3MzM1NzQsImV4cCI6MjA0NzMwOTU3NH0.eZA6Mfmztb3o8Qz20i8C9GRCG9hqfGfgWQM4eNlfZEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);